[0m13:29:01.284654 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FBEC8D7440>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FBEC8D5EB0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FBEC3A5700>]}


============================== 13:29:01.307432 | d02b5648-454a-45ed-a7f3-0dd3f64b30cb ==============================
[0m13:29:01.307432 [info ] [MainThread]: Running with dbt=1.10.8
[0m13:29:01.315639 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\23521\\.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'invocation_command': 'dbt init linkedin_job_market', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m13:29:01.346333 [info ] [MainThread]: Creating dbt configuration folder at C:\Users\23521\.dbt
[0m13:29:01.355853 [debug] [MainThread]: Starter project path: D:\WorkSpace\projects\linkedin_dataplatform\venv\Lib\site-packages\dbt\include\starter_project
[0m13:29:01.385034 [info ] [MainThread]: 
Your new dbt project "linkedin_job_market" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m13:29:01.385034 [info ] [MainThread]: Setting up your profile.
[0m13:32:23.250006 [info ] [MainThread]: Profile linkedin_job_market written to C:\Users\23521\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m13:32:23.250006 [debug] [MainThread]: Command `dbt init` succeeded at 13:32:23.250006 after 202.08 seconds
[0m13:32:23.250006 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FBEBDC05F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FBECD7BF80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FBEC17CEC0>]}
[0m13:32:23.250006 [debug] [MainThread]: Flushing usage events
[0m13:32:24.395343 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m13:38:15.159952 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020367587FB0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002036A50A360>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002036A508170>]}


============================== 13:38:15.165561 | 8a32156b-9871-42c6-9391-f305f5964b31 ==============================
[0m13:38:15.165561 [info ] [MainThread]: Running with dbt=1.10.8
[0m13:38:15.165561 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\23521\\.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt debug --target dev', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'send_anonymous_usage_stats': 'True'}
[0m13:38:15.203750 [info ] [MainThread]: dbt version: 1.10.8
[0m13:38:15.204836 [info ] [MainThread]: python version: 3.12.9
[0m13:38:15.205355 [info ] [MainThread]: python path: D:\WorkSpace\projects\linkedin_dataplatform\venv\Scripts\python.exe
[0m13:38:15.205355 [info ] [MainThread]: os info: Windows-11-10.0.22631-SP0
[0m13:38:15.273781 [info ] [MainThread]: Using profiles dir at C:\Users\23521\.dbt
[0m13:38:15.273781 [info ] [MainThread]: Using profiles.yml file at C:\Users\23521\.dbt\profiles.yml
[0m13:38:15.273781 [info ] [MainThread]: Using dbt_project.yml file at D:\WorkSpace\projects\linkedin_dataplatform\etl_pipeline\dbt_project.yml
[0m13:38:15.279802 [info ] [MainThread]: adapter type: postgres
[0m13:38:15.279802 [info ] [MainThread]: adapter version: 1.9.0
[0m13:38:15.279802 [info ] [MainThread]: Configuration:
[0m13:38:15.279802 [info ] [MainThread]:   profiles.yml file [[32mOK found and valid[0m]
[0m13:38:15.279802 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m13:38:15.279802 [info ] [MainThread]: Required dependencies:
[0m13:38:15.283416 [debug] [MainThread]: Executing "git --help"
[0m13:38:15.314297 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--no-lazy-fetch]\n           [--no-optional-locks] [--no-advice] [--bare] [--git-dir=<path>]\n           [--work-tree=<path>] [--namespace=<name>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone      Clone a repository into a new directory\n   init       Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add        Add file contents to the index\n   mv         Move or rename a file, a directory, or a symlink\n   restore    Restore working tree files\n   rm         Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect     Use binary search to find the commit that introduced a bug\n   diff       Show changes between commits, commit and working tree, etc\n   grep       Print lines matching a pattern\n   log        Show commit logs\n   show       Show various types of objects\n   status     Show the working tree status\n\ngrow, mark and tweak your common history\n   backfill   Download missing objects in a partial clone\n   branch     List, create, or delete branches\n   commit     Record changes to the repository\n   merge      Join two or more development histories together\n   rebase     Reapply commits on top of another base tip\n   reset      Reset current HEAD to the specified state\n   switch     Switch branches\n   tag        Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch      Download objects and refs from another repository\n   pull       Fetch from and integrate with another repository or a local branch\n   push       Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m13:38:15.314297 [debug] [MainThread]: STDERR: "b''"
[0m13:38:15.318788 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m13:38:15.318788 [info ] [MainThread]: Connection:
[0m13:38:15.318788 [info ] [MainThread]:   host: 5432
[0m13:38:15.318788 [info ] [MainThread]:   port: 5432
[0m13:38:15.318788 [info ] [MainThread]:   user: postgres
[0m13:38:15.318788 [info ] [MainThread]:   database: analytics
[0m13:38:15.318788 [info ] [MainThread]:   schema: analytics
[0m13:38:15.318788 [info ] [MainThread]:   connect_timeout: 10
[0m13:38:15.318788 [info ] [MainThread]:   role: None
[0m13:38:15.324870 [info ] [MainThread]:   search_path: None
[0m13:38:15.325207 [info ] [MainThread]:   keepalives_idle: 0
[0m13:38:15.326388 [info ] [MainThread]:   sslmode: None
[0m13:38:15.327398 [info ] [MainThread]:   sslcert: None
[0m13:38:15.327398 [info ] [MainThread]:   sslkey: None
[0m13:38:15.328399 [info ] [MainThread]:   sslrootcert: None
[0m13:38:15.328399 [info ] [MainThread]:   application_name: dbt
[0m13:38:15.329401 [info ] [MainThread]:   retries: 1
[0m13:38:15.330095 [info ] [MainThread]: Registered adapter: postgres=1.9.0
[0m13:38:15.767582 [debug] [MainThread]: Acquiring new postgres connection 'debug'
[0m13:38:18.516188 [debug] [MainThread]: Using postgres connection "debug"
[0m13:38:18.516188 [debug] [MainThread]: On debug: select 1 as id
[0m13:38:18.516188 [debug] [MainThread]: Opening a new connection, currently in state init
[0m13:38:25.766159 [debug] [MainThread]: Postgres adapter: Got a retryable error when attempting to open a postgres connection.
1 attempts remaining. Retrying in 0 seconds.
Error:
could not translate host name "5432" to address: No such host is known. 

[0m13:38:33.035761 [debug] [MainThread]: Postgres adapter: Error running SQL: select 1 as id
[0m13:38:33.035761 [debug] [MainThread]: Postgres adapter: Rolling back transaction.
[0m13:38:33.035761 [debug] [MainThread]: On debug: No close available on handle
[0m13:38:33.035761 [info ] [MainThread]:   Connection test: [[31mERROR[0m]

[0m13:38:33.035761 [info ] [MainThread]: [31m2 checks failed:[0m
[0m13:38:33.035761 [info ] [MainThread]: Project loading failed for the following reason:
 project path <D:\WorkSpace\projects\linkedin_dataplatform\etl_pipeline\dbt_project.yml> not found

[0m13:38:33.035761 [info ] [MainThread]: dbt was unable to connect to the specified database.
The database returned the following error:

  >Database Error
  could not translate host name "5432" to address: No such host is known. 
  

Check your database credentials and try again. For more information, visit:
https://docs.getdbt.com/docs/configure-your-profile


[0m13:38:33.035761 [debug] [MainThread]: Command `dbt debug` failed at 13:38:33.035761 after 18.00 seconds
[0m13:38:33.035761 [debug] [MainThread]: Connection 'debug' was properly closed.
[0m13:38:33.035761 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020367587FB0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002036B2360F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002036C637590>]}
[0m13:38:33.041311 [debug] [MainThread]: Flushing usage events
[0m13:38:34.244132 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m13:38:58.742786 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000215421F4410>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000215422B6960>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002153E84A720>]}


============================== 13:38:58.742786 | 08a8d57f-9f47-4e06-9066-838098691d61 ==============================
[0m13:38:58.742786 [info ] [MainThread]: Running with dbt=1.10.8
[0m13:38:58.742786 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\23521\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'invocation_command': 'dbt debug --target dev', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m13:38:58.779655 [info ] [MainThread]: dbt version: 1.10.8
[0m13:38:58.780665 [info ] [MainThread]: python version: 3.12.9
[0m13:38:58.781018 [info ] [MainThread]: python path: D:\WorkSpace\projects\linkedin_dataplatform\venv\Scripts\python.exe
[0m13:38:58.781532 [info ] [MainThread]: os info: Windows-11-10.0.22631-SP0
[0m13:38:58.845305 [info ] [MainThread]: Using profiles dir at C:\Users\23521\.dbt
[0m13:38:58.845305 [info ] [MainThread]: Using profiles.yml file at C:\Users\23521\.dbt\profiles.yml
[0m13:38:58.845305 [info ] [MainThread]: Using dbt_project.yml file at D:\WorkSpace\projects\linkedin_dataplatform\etl_pipeline\dbt_project.yml
[0m13:38:58.845305 [info ] [MainThread]: adapter type: postgres
[0m13:38:58.845305 [info ] [MainThread]: adapter version: 1.9.0
[0m13:38:58.845305 [info ] [MainThread]: Configuration:
[0m13:38:58.845305 [info ] [MainThread]:   profiles.yml file [[32mOK found and valid[0m]
[0m13:38:58.845305 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m13:38:58.854935 [info ] [MainThread]: Required dependencies:
[0m13:38:58.855456 [debug] [MainThread]: Executing "git --help"
[0m13:38:58.886478 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--no-lazy-fetch]\n           [--no-optional-locks] [--no-advice] [--bare] [--git-dir=<path>]\n           [--work-tree=<path>] [--namespace=<name>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone      Clone a repository into a new directory\n   init       Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add        Add file contents to the index\n   mv         Move or rename a file, a directory, or a symlink\n   restore    Restore working tree files\n   rm         Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect     Use binary search to find the commit that introduced a bug\n   diff       Show changes between commits, commit and working tree, etc\n   grep       Print lines matching a pattern\n   log        Show commit logs\n   show       Show various types of objects\n   status     Show the working tree status\n\ngrow, mark and tweak your common history\n   backfill   Download missing objects in a partial clone\n   branch     List, create, or delete branches\n   commit     Record changes to the repository\n   merge      Join two or more development histories together\n   rebase     Reapply commits on top of another base tip\n   reset      Reset current HEAD to the specified state\n   switch     Switch branches\n   tag        Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch      Download objects and refs from another repository\n   pull       Fetch from and integrate with another repository or a local branch\n   push       Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m13:38:58.886613 [debug] [MainThread]: STDERR: "b''"
[0m13:38:58.887461 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m13:38:58.888015 [info ] [MainThread]: Connection:
[0m13:38:58.888213 [info ] [MainThread]:   host: de_psql
[0m13:38:58.888213 [info ] [MainThread]:   port: 5433
[0m13:38:58.889239 [info ] [MainThread]:   user: admin
[0m13:38:58.889746 [info ] [MainThread]:   database: postgres
[0m13:38:58.889746 [info ] [MainThread]:   schema: analysis
[0m13:38:58.890757 [info ] [MainThread]:   connect_timeout: 10
[0m13:38:58.891374 [info ] [MainThread]:   role: None
[0m13:38:58.891374 [info ] [MainThread]:   search_path: None
[0m13:38:58.891374 [info ] [MainThread]:   keepalives_idle: 0
[0m13:38:58.891374 [info ] [MainThread]:   sslmode: None
[0m13:38:58.893516 [info ] [MainThread]:   sslcert: None
[0m13:38:58.893516 [info ] [MainThread]:   sslkey: None
[0m13:38:58.894527 [info ] [MainThread]:   sslrootcert: None
[0m13:38:58.894527 [info ] [MainThread]:   application_name: dbt
[0m13:38:58.894527 [info ] [MainThread]:   retries: 1
[0m13:38:58.896091 [info ] [MainThread]: Registered adapter: postgres=1.9.0
[0m13:38:59.214712 [debug] [MainThread]: Acquiring new postgres connection 'debug'
[0m13:38:59.307335 [debug] [MainThread]: Using postgres connection "debug"
[0m13:38:59.307335 [debug] [MainThread]: On debug: select 1 as id
[0m13:38:59.307335 [debug] [MainThread]: Opening a new connection, currently in state init
[0m13:39:06.550681 [debug] [MainThread]: Postgres adapter: Got a retryable error when attempting to open a postgres connection.
1 attempts remaining. Retrying in 0 seconds.
Error:
could not translate host name "de_psql" to address: No such host is known. 

[0m13:39:13.793464 [debug] [MainThread]: Postgres adapter: Error running SQL: select 1 as id
[0m13:39:13.793464 [debug] [MainThread]: Postgres adapter: Rolling back transaction.
[0m13:39:13.793464 [debug] [MainThread]: On debug: No close available on handle
[0m13:39:13.793464 [info ] [MainThread]:   Connection test: [[31mERROR[0m]

[0m13:39:13.793464 [info ] [MainThread]: [31m2 checks failed:[0m
[0m13:39:13.793464 [info ] [MainThread]: Project loading failed for the following reason:
 project path <D:\WorkSpace\projects\linkedin_dataplatform\etl_pipeline\dbt_project.yml> not found

[0m13:39:13.793464 [info ] [MainThread]: dbt was unable to connect to the specified database.
The database returned the following error:

  >Database Error
  could not translate host name "de_psql" to address: No such host is known. 
  

Check your database credentials and try again. For more information, visit:
https://docs.getdbt.com/docs/configure-your-profile


[0m13:39:13.793464 [debug] [MainThread]: Command `dbt debug` failed at 13:39:13.793464 after 15.18 seconds
[0m13:39:13.793464 [debug] [MainThread]: Connection 'debug' was properly closed.
[0m13:39:13.793464 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000215425A96A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000215427014F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002154256D160>]}
[0m13:39:13.793464 [debug] [MainThread]: Flushing usage events
[0m13:39:14.900054 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m13:39:46.720727 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C358B2B860>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C35913F740>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C35B75DAC0>]}


============================== 13:39:46.721248 | 5744e45e-99ca-4096-b02b-53810b4ac94a ==============================
[0m13:39:46.721248 [info ] [MainThread]: Running with dbt=1.10.8
[0m13:39:46.721248 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\23521\\.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt run', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m13:39:46.727861 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path D:\WorkSpace\projects\linkedin_dataplatform\etl_pipeline\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m13:39:46.727861 [debug] [MainThread]: Command `dbt run` failed at 13:39:46.727861 after 0.12 seconds
[0m13:39:46.727861 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C35B7F5130>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C358B2B860>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C35B75CF50>]}
[0m13:39:46.727861 [debug] [MainThread]: Flushing usage events
[0m13:39:47.876489 [debug] [MainThread]: An error was encountered while trying to flush usage events
